### ISSUE TITLE
Add Demo

### ISSUE THREAD

**Issue by morkev** [sabinaixchelgm/google_clone#1]
As a suggestion, you should host your project on GitHub Pages and leave it as an interactive demo for your client. I can help you – let me know!

**Comment by sabinaixchelgm** [comment]
Hola kheee  jajaja

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by morkev** [comment]
En lo que menos esperaba, ya habías montado un sitio para el proyecto :/, por eso lo he cerrao. Ya no sabia de tu existencia!! Mandame un mensaje por email – el mio lo encuentras en mi perfil jajaja. Bien boomer con el email.
